# Generated by Django 2.2.2 on 2019-07-23 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 3, 24, 22, 559512), verbose_name='date published'),
        ),
    ]
